version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      next:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
