-- CreateTable
CREATE TABLE `USERS` (
    `UserID` INTEGER NOT NULL AUTO_INCREMENT,
    `FirstName` VARCHAR(100) NOT NULL,
    `MiddleName` VARCHAR(100) NULL,
    `LastName` VARCHAR(100) NOT NULL,
    `Username` VARCHAR(50) NOT NULL,
    `Email` VARCHAR(100) NOT NULL,
    `UserPassword` VARCHAR(255) NOT NULL,
    `DOB` DATE NOT NULL,
    `ContactNo` VARCHAR(13) NOT NULL,
    `DateTimeRegistered` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `LastLogin` DATETIME(3) NULL,
    `STATUS` ENUM('Active', 'Inactive') NOT NULL DEFAULT 'Active',
    `ProfilePictureURL` VARCHAR(255) NULL,

    UNIQUE INDEX `USERS_Username_key`(`Username`),
    UNIQUE INDEX `USERS_Email_key`(`Email`),
    PRIMARY KEY (`UserID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ROLES` (
    `RoleID` INTEGER NOT NULL AUTO_INCREMENT,
    `RoleName` VARCHAR(50) NOT NULL,

    UNIQUE INDEX `ROLES_RoleName_key`(`RoleName`),
    PRIMARY KEY (`RoleID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_ROLES` (
    `UserRoleID` INTEGER NOT NULL AUTO_INCREMENT,
    `UserID` INTEGER NOT NULL,
    `RoleID` INTEGER NOT NULL,

    UNIQUE INDEX `USER_ROLES_UserID_RoleID_key`(`UserID`, `RoleID`),
    PRIMARY KEY (`UserRoleID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SELLERS` (
    `SellerID` INTEGER NOT NULL AUTO_INCREMENT,
    `UserID` INTEGER NOT NULL,
    `ShopName` VARCHAR(255) NOT NULL,
    `ShopDescription` TEXT NULL,
    `ShopLogoURL` VARCHAR(255) NULL,
    `ShopStatus` ENUM('Active', 'Inactive', 'Banned') NOT NULL DEFAULT 'Active',
    `RegisteredAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `SELLERS_UserID_key`(`UserID`),
    UNIQUE INDEX `SELLERS_ShopName_key`(`ShopName`),
    PRIMARY KEY (`SellerID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROVINCE` (
    `ProvinceID` INTEGER NOT NULL AUTO_INCREMENT,
    `Province` VARCHAR(100) NOT NULL,

    UNIQUE INDEX `PROVINCE_Province_key`(`Province`),
    PRIMARY KEY (`ProvinceID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CITY` (
    `CityID` INTEGER NOT NULL AUTO_INCREMENT,
    `City` VARCHAR(100) NOT NULL,
    `PostalCode` VARCHAR(10) NOT NULL,
    `ProvinceID` INTEGER NOT NULL,

    UNIQUE INDEX `CITY_City_ProvinceID_key`(`City`, `ProvinceID`),
    PRIMARY KEY (`CityID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BARANGAY` (
    `BarangayID` INTEGER NOT NULL AUTO_INCREMENT,
    `Barangay` VARCHAR(100) NOT NULL,
    `CityID` INTEGER NOT NULL,

    UNIQUE INDEX `BARANGAY_Barangay_CityID_key`(`Barangay`, `CityID`),
    PRIMARY KEY (`BarangayID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ADDRESS` (
    `AddressID` INTEGER NOT NULL AUTO_INCREMENT,
    `Street` VARCHAR(255) NOT NULL,
    `BarangayID` INTEGER NOT NULL,

    UNIQUE INDEX `ADDRESS_Street_BarangayID_key`(`Street`, `BarangayID`),
    PRIMARY KEY (`AddressID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_ADDRESSES` (
    `UserAddressID` INTEGER NOT NULL AUTO_INCREMENT,
    `UserID` INTEGER NOT NULL,
    `AddressID` INTEGER NOT NULL,
    `AddressType` ENUM('Home', 'Work') NULL,
    `isDefault` BOOLEAN NOT NULL DEFAULT false,

    UNIQUE INDEX `USER_ADDRESSES_UserID_AddressID_key`(`UserID`, `AddressID`),
    PRIMARY KEY (`UserAddressID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AGE_RANGE` (
    `AgeRangeID` INTEGER NOT NULL AUTO_INCREMENT,
    `MinAge` INTEGER NOT NULL,
    `MaxAge` INTEGER NULL,
    `Label` VARCHAR(255) NULL,

    PRIMARY KEY (`AgeRangeID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CATEGORIES` (
    `CategoryID` INTEGER NOT NULL AUTO_INCREMENT,
    `CategoryName` VARCHAR(255) NOT NULL,
    `DESCRIPTION` TEXT NULL,

    UNIQUE INDEX `CATEGORIES_CategoryName_key`(`CategoryName`),
    PRIMARY KEY (`CategoryID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PRODUCT` (
    `ProductID` INTEGER NOT NULL AUTO_INCREMENT,
    `SellerID` INTEGER NOT NULL,
    `Name` VARCHAR(100) NOT NULL,
    `Description` TEXT NOT NULL,
    `ImageURL` VARCHAR(255) NOT NULL,
    `Price` DECIMAL(10, 2) NOT NULL,
    `CategoryID` INTEGER NOT NULL,
    `StockQuantity` INTEGER NOT NULL DEFAULT 1,
    `Status` ENUM('Available', 'Unavailable') NOT NULL DEFAULT 'Available',
    `DateAdded` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `LastUpdated` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `AgeRangeID` INTEGER NOT NULL,

    UNIQUE INDEX `PRODUCT_SellerID_Name_key`(`SellerID`, `Name`),
    PRIMARY KEY (`ProductID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PRODUCT_DETAILS` (
    `DetailID` INTEGER NOT NULL AUTO_INCREMENT,
    `ProductID` INTEGER NOT NULL,
    `Height` DECIMAL(10, 2) NULL,
    `Weight` DECIMAL(10, 2) NULL,
    `Width` DECIMAL(10, 2) NULL,
    `Length` DECIMAL(10, 2) NULL,
    `Material` VARCHAR(255) NULL,

    UNIQUE INDEX `PRODUCT_DETAILS_ProductID_key`(`ProductID`),
    PRIMARY KEY (`DetailID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ORDERS` (
    `OrderID` INTEGER NOT NULL AUTO_INCREMENT,
    `UserID` INTEGER NOT NULL,
    `OrderDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `OrderStatus` ENUM('Pending', 'InTransit', 'Completed') NOT NULL DEFAULT 'Pending',
    `TotalAmount` DECIMAL(10, 2) NOT NULL,
    `ShippingFee` DECIMAL(10, 2) NOT NULL DEFAULT 58,
    `UserAddressID` INTEGER NOT NULL,
    `Notes` TEXT NULL,

    PRIMARY KEY (`OrderID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ORDER_ITEMS` (
    `OrderItemID` INTEGER NOT NULL AUTO_INCREMENT,
    `OrderID` INTEGER NOT NULL,
    `ProductID` INTEGER NOT NULL,
    `quantity` INTEGER NOT NULL DEFAULT 1,
    `Price` DECIMAL(10, 2) NOT NULL,
    `OrderItemStatus` ENUM('Pending', 'InTransit', 'Completed') NOT NULL DEFAULT 'Pending',
    `DateDelivered` DATETIME(3) NULL,

    UNIQUE INDEX `ORDER_ITEMS_OrderID_ProductID_key`(`OrderID`, `ProductID`),
    PRIMARY KEY (`OrderItemID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PAYMENT` (
    `PaymentID` INTEGER NOT NULL AUTO_INCREMENT,
    `OrderID` INTEGER NOT NULL,
    `PaymentMethod` ENUM('COD', 'GCash') NULL,
    `PaymentStatus` ENUM('Paid', 'Unpaid') NOT NULL DEFAULT 'Unpaid',
    `PaymentAmount` DECIMAL(10, 2) NOT NULL,
    `PaymentDate` DATETIME(3) NULL,

    UNIQUE INDEX `PAYMENT_OrderID_key`(`OrderID`),
    PRIMARY KEY (`PaymentID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CART` (
    `CartID` INTEGER NOT NULL AUTO_INCREMENT,
    `UserID` INTEGER NOT NULL,

    UNIQUE INDEX `CART_UserID_key`(`UserID`),
    PRIMARY KEY (`CartID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CART_ITEMS` (
    `CartItemID` INTEGER NOT NULL AUTO_INCREMENT,
    `CartID` INTEGER NOT NULL,
    `ProductID` INTEGER NOT NULL,
    `quantity` INTEGER NOT NULL DEFAULT 1,
    `DateAdded` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `CART_ITEMS_CartID_ProductID_key`(`CartID`, `ProductID`),
    PRIMARY KEY (`CartItemID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `REVIEWS` (
    `ReviewID` INTEGER NOT NULL AUTO_INCREMENT,
    `UserID` INTEGER NOT NULL,
    `OrderItemID` INTEGER NOT NULL,
    `Rating` ENUM('one', 'two', 'three', 'four', 'five') NOT NULL DEFAULT 'five',
    `Comment` TEXT NULL,
    `DatePosted` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `REVIEWS_UserID_OrderItemID_key`(`UserID`, `OrderItemID`),
    PRIMARY KEY (`ReviewID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `COMMISSION` (
    `CommissionID` INTEGER NOT NULL AUTO_INCREMENT,
    `SellerID` INTEGER NOT NULL,
    `OrderItemID` INTEGER NOT NULL,
    `CommissionAmount` DECIMAL(10, 2) NOT NULL,
    `Status` ENUM('Paid', 'Unpaid') NOT NULL DEFAULT 'Unpaid',
    `DatePaid` DATETIME(3) NULL,

    PRIMARY KEY (`CommissionID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `USER_ROLES` ADD CONSTRAINT `USER_ROLES_UserID_fkey` FOREIGN KEY (`UserID`) REFERENCES `USERS`(`UserID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_ROLES` ADD CONSTRAINT `USER_ROLES_RoleID_fkey` FOREIGN KEY (`RoleID`) REFERENCES `ROLES`(`RoleID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SELLERS` ADD CONSTRAINT `SELLERS_UserID_fkey` FOREIGN KEY (`UserID`) REFERENCES `USERS`(`UserID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CITY` ADD CONSTRAINT `CITY_ProvinceID_fkey` FOREIGN KEY (`ProvinceID`) REFERENCES `PROVINCE`(`ProvinceID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BARANGAY` ADD CONSTRAINT `BARANGAY_CityID_fkey` FOREIGN KEY (`CityID`) REFERENCES `CITY`(`CityID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ADDRESS` ADD CONSTRAINT `ADDRESS_BarangayID_fkey` FOREIGN KEY (`BarangayID`) REFERENCES `BARANGAY`(`BarangayID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_ADDRESSES` ADD CONSTRAINT `USER_ADDRESSES_UserID_fkey` FOREIGN KEY (`UserID`) REFERENCES `USERS`(`UserID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_ADDRESSES` ADD CONSTRAINT `USER_ADDRESSES_AddressID_fkey` FOREIGN KEY (`AddressID`) REFERENCES `ADDRESS`(`AddressID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRODUCT` ADD CONSTRAINT `PRODUCT_SellerID_fkey` FOREIGN KEY (`SellerID`) REFERENCES `SELLERS`(`SellerID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRODUCT` ADD CONSTRAINT `PRODUCT_CategoryID_fkey` FOREIGN KEY (`CategoryID`) REFERENCES `CATEGORIES`(`CategoryID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRODUCT` ADD CONSTRAINT `PRODUCT_AgeRangeID_fkey` FOREIGN KEY (`AgeRangeID`) REFERENCES `AGE_RANGE`(`AgeRangeID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRODUCT_DETAILS` ADD CONSTRAINT `PRODUCT_DETAILS_ProductID_fkey` FOREIGN KEY (`ProductID`) REFERENCES `PRODUCT`(`ProductID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORDERS` ADD CONSTRAINT `ORDERS_UserID_fkey` FOREIGN KEY (`UserID`) REFERENCES `USERS`(`UserID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORDERS` ADD CONSTRAINT `ORDERS_UserAddressID_fkey` FOREIGN KEY (`UserAddressID`) REFERENCES `USER_ADDRESSES`(`UserAddressID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORDER_ITEMS` ADD CONSTRAINT `ORDER_ITEMS_OrderID_fkey` FOREIGN KEY (`OrderID`) REFERENCES `ORDERS`(`OrderID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORDER_ITEMS` ADD CONSTRAINT `ORDER_ITEMS_ProductID_fkey` FOREIGN KEY (`ProductID`) REFERENCES `PRODUCT`(`ProductID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PAYMENT` ADD CONSTRAINT `PAYMENT_OrderID_fkey` FOREIGN KEY (`OrderID`) REFERENCES `ORDERS`(`OrderID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CART` ADD CONSTRAINT `CART_UserID_fkey` FOREIGN KEY (`UserID`) REFERENCES `USERS`(`UserID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CART_ITEMS` ADD CONSTRAINT `CART_ITEMS_CartID_fkey` FOREIGN KEY (`CartID`) REFERENCES `CART`(`CartID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CART_ITEMS` ADD CONSTRAINT `CART_ITEMS_ProductID_fkey` FOREIGN KEY (`ProductID`) REFERENCES `PRODUCT`(`ProductID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REVIEWS` ADD CONSTRAINT `REVIEWS_UserID_fkey` FOREIGN KEY (`UserID`) REFERENCES `USERS`(`UserID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REVIEWS` ADD CONSTRAINT `REVIEWS_OrderItemID_fkey` FOREIGN KEY (`OrderItemID`) REFERENCES `ORDER_ITEMS`(`OrderItemID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `COMMISSION` ADD CONSTRAINT `COMMISSION_SellerID_fkey` FOREIGN KEY (`SellerID`) REFERENCES `SELLERS`(`SellerID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `COMMISSION` ADD CONSTRAINT `COMMISSION_OrderItemID_fkey` FOREIGN KEY (`OrderItemID`) REFERENCES `ORDER_ITEMS`(`OrderItemID`) ON DELETE CASCADE ON UPDATE CASCADE;
